package suhockii.dev.bookfinder.di

object DI {
    const val APP_SCOPE = "APP_SCOPE"
    const val SPLASH_ACTIVITY_SCOPE = "SPLASH_ACTIVITY_SCOPE"
    const val INITIALIZATION_ACTIVITY_SCOPE = "INITIALIZATION_ACTIVITY_SCOPE"
    const val CATEGORIES_ACTIVITY_SCOPE = "CATEGORIES_ACTIVITY_SCOPE"
    const val BOOKS_ACTIVITY_SCOPE = "BOOKS_ACTIVITY_SCOPE"
}